mysql:
  dsn: "root:jsm1234@tcp(192.168.159.132:3306)/ginhomework?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  maxIdleConns: 10
  maxOpenConns: 100
jwt:
  jwtSecret: "53f01311-b030-b150-1e2a-610f94c39693"